### Comment Endpoints

### Получение списка комментариев для предложения
GET http://localhost:5000/comments/offer/6724a812acf9ba2baac3154c HTTP/1.1
Content-Type: application/json

### Добавление комментария для предложения

POST http://localhost:5000/comments/offer/6724a812acf9ba2baac3154c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3MjRlYWVmODBmYTlkZGIyYjFiZWYzMyIsImVtYWlsIjoiYm9iQGh0bWxhY2FkZW15LmNvbSIsIm5hbWUiOiJib2IiLCJpYXQiOjE3MzA0NzI4MDEsImV4cCI6MTczMDY0NTYwMX0.zA6WYp5a58yoyAWm-ge2v-tUhGFHK8EdEMGGJLocsUQ

{
  "comment": "Это новый комментарий",
  "rating": 5
}
